server:
  port: 8877
  context-path: /article
eureka:
  client: 
    healthcheck:
      enabled:true
    service-url:
      defaultZone: http://user:password123@www.renxl.club:10020/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}   
    lease-renewal-interval-in-seconds: 5      # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 10  # 发呆时间，即服务续约到期时间（缺省为90s）

# 个人对eureka租期续约的理解，客户端定期注册，服务端定期扫描，客户端还有一个注册失败的清除时间


feign:
  hystrix:
    enabled: true # 默认启用
#  client:
#    default:
#      #这里时间一定要调长，否则feign客户端会报ReadTimeOut  服务端报Error parsing HTTP request header
#      connectTimeout: 60000
#      readTimeout: 60000
#      loggerLevel: basic

# --------------------------- mysql start -------------------------
spring:
  application:
    name: article
#  datasource:
#    url: jdbc:mysql://47.104.88.31:3306/axin20180716?useUnicode=true&amp;characterEncoding=utf-8
#    username: root
#    password: abcde12345
#    driverClassName: com.mysql.jdbc.Driver
# --------------------------- mysql end ---------------------------
#
#
# --------------------------- mybatis start -------------------------
#
mybatis:
  mapperLocations: classpath*:club.renxl.www.blog.article.mapper/*.xml
  typeAliasesPackage: club.renxl.www.blog.article.domain
  #pagehelper分页插件配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
# --------------------------- mybatis end ---------------------------
# 暂时配置，后期配置到配置服务器
images:
  base:
    url: http://www.renxl.club/ims/blog/
    
    
    
multipart:
  maxFileSize: 10Mb
  maxRequestSize: 100Mb
  
  