# 集群1
security:
  basic:
    enabled: true
  user:
    name: user
    password: password123
server:
  port: 9002
 
spring:
  application:
    name: eurekaServer
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password123@localhost:9001/eureka
   
