server:
  port: 10030
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/renxinlin/config #（也可以是不同仓库的名称，这样隔离性强，项目之间不可见）
  application:
    name: config-server