package club.renxl.www.blog.article.domain;

import java.util.Date;

public class Comment {
    /**  */
    private Integer id;

    /** 主题id */
    private Integer topicId;

    /** 1为课程，2为集会，3为商品 */
    private Byte topicType;

    /** 评论者id，一般为会员表的id */
    private Integer fromUid;

    /** 冗余用户昵称 */
    private String nickname;

    /** 冗余用户头像 */
    private String thumbImg;

    /** 是否置顶评论，1为置顶，0为不置顶 */
    private Byte isTop;

    /** 是否为热评，1为热评 */
    private Byte isHot;

    /** 评论被点赞的次数 */
    private Integer likeNum;

    /** 评论被回复的次数 */
    private Integer replyNum;

    /** 是否回复0没回复1有回复 */
    private Byte isReply;

    /** 评论状态，-1为删除，0为待审核，1为已发布 */
    private Byte status;

    /** 创建时间 */
    private Date createTime;

    /** 评论内容 */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column axin_blogs_comment.id
     *
     * @return the value of axin_blogs_comment.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column axin_blogs_comment.id
     *
     * @param id the value for axin_blogs_comment.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column axin_blogs_comment.topic_id
     *
     * @return the value of axin_blogs_comment.topic_id
     *
     * @mbggenerated
     */
    public Integer getTopicId() {
        return topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column axin_blogs_comment.topic_id
     *
     * @param topicId the value for axin_blogs_comment.topic_id
     *
     * @mbggenerated
     */
    public void setTopicId(Integer topicId) {
        this.topicId = topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column axin_blogs_comment.topic_type
     *
     * @return the value of axin_blogs_comment.topic_type
     *
     * @mbggenerated
     */
    public Byte getTopicType() {
        return topicType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column axin_blogs_comment.topic_type
     *
     * @param topicType the value for axin_blogs_comment.topic_type
     *
     * @mbggenerated
     */
    public void setTopicType(Byte topicType) {
        this.topicType = topicType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column axin_blogs_comment.from_uid
     *
     * @return the value of axin_blogs_comment.from_uid
     *
     * @mbggenerated
     */
    public Integer getFromUid() {
        return fromUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column axin_blogs_comment.from_uid
     *
     * @param fromUid the value for axin_blogs_comment.from_uid
     *
     * @mbggenerated
     */
    public void setFromUid(Integer fromUid) {
        this.fromUid = fromUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column axin_blogs_comment.nickname
     *
     * @return the value of axin_blogs_comment.nickname
     *
     * @mbggenerated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column axin_blogs_comment.nickname
     *
     * @param nickname the value for axin_blogs_comment.nickname
     *
     * @mbggenerated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column axin_blogs_comment.thumb_img
     *
     * @return the value of axin_blogs_comment.thumb_img
     *
     * @mbggenerated
     */
    public String getThumbImg() {
        return thumbImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column axin_blogs_comment.thumb_img
     *
     * @param thumbImg the value for axin_blogs_comment.thumb_img
     *
     * @mbggenerated
     */
    public void setThumbImg(String thumbImg) {
        this.thumbImg = thumbImg == null ? null : thumbImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column axin_blogs_comment.is_top
     *
     * @return the value of axin_blogs_comment.is_top
     *
     * @mbggenerated
     */
    public Byte getIsTop() {
        return isTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column axin_blogs_comment.is_top
     *
     * @param isTop the value for axin_blogs_comment.is_top
     *
     * @mbggenerated
     */
    public void setIsTop(Byte isTop) {
        this.isTop = isTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column axin_blogs_comment.is_hot
     *
     * @return the value of axin_blogs_comment.is_hot
     *
     * @mbggenerated
     */
    public Byte getIsHot() {
        return isHot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column axin_blogs_comment.is_hot
     *
     * @param isHot the value for axin_blogs_comment.is_hot
     *
     * @mbggenerated
     */
    public void setIsHot(Byte isHot) {
        this.isHot = isHot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column axin_blogs_comment.like_num
     *
     * @return the value of axin_blogs_comment.like_num
     *
     * @mbggenerated
     */
    public Integer getLikeNum() {
        return likeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column axin_blogs_comment.like_num
     *
     * @param likeNum the value for axin_blogs_comment.like_num
     *
     * @mbggenerated
     */
    public void setLikeNum(Integer likeNum) {
        this.likeNum = likeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column axin_blogs_comment.reply_num
     *
     * @return the value of axin_blogs_comment.reply_num
     *
     * @mbggenerated
     */
    public Integer getReplyNum() {
        return replyNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column axin_blogs_comment.reply_num
     *
     * @param replyNum the value for axin_blogs_comment.reply_num
     *
     * @mbggenerated
     */
    public void setReplyNum(Integer replyNum) {
        this.replyNum = replyNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column axin_blogs_comment.is_reply
     *
     * @return the value of axin_blogs_comment.is_reply
     *
     * @mbggenerated
     */
    public Byte getIsReply() {
        return isReply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column axin_blogs_comment.is_reply
     *
     * @param isReply the value for axin_blogs_comment.is_reply
     *
     * @mbggenerated
     */
    public void setIsReply(Byte isReply) {
        this.isReply = isReply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column axin_blogs_comment.status
     *
     * @return the value of axin_blogs_comment.status
     *
     * @mbggenerated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column axin_blogs_comment.status
     *
     * @param status the value for axin_blogs_comment.status
     *
     * @mbggenerated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column axin_blogs_comment.create_time
     *
     * @return the value of axin_blogs_comment.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column axin_blogs_comment.create_time
     *
     * @param createTime the value for axin_blogs_comment.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column axin_blogs_comment.content
     *
     * @return the value of axin_blogs_comment.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column axin_blogs_comment.content
     *
     * @param content the value for axin_blogs_comment.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}