package club.renxl.www.blog.article.domain;

import java.util.Date;

public class Reply {
    /**  */
    private Integer id;

    /** 根评论id */
    private Integer commentId;

    /** 1为回复评论，2为回复别人的回复 */
    private Byte replyType;

    /** 回复目标id，reply_type为1时，是comment_id，reply_type为2时为回复表的id */
    private Integer replyId;

    /** 回复目标id */
    private Integer toUid;

    /** 回复用户id */
    private Integer fromUid;

    /** 回复者的头像 */
    private String fromThumbImg;

    /** 回复者的昵称 */
    private String fromNickname;

    /** 评论时间 */
    private Date createTime;

    /** 冗余回复对象的昵称 */
    private String toNickname;

    /** 0为普通回复，1为后台管理员回复 */
    private Byte isAuthor;

    /** 回复内容 */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column axin_blogs_reply.id
     *
     * @return the value of axin_blogs_reply.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column axin_blogs_reply.id
     *
     * @param id the value for axin_blogs_reply.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column axin_blogs_reply.comment_id
     *
     * @return the value of axin_blogs_reply.comment_id
     *
     * @mbggenerated
     */
    public Integer getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column axin_blogs_reply.comment_id
     *
     * @param commentId the value for axin_blogs_reply.comment_id
     *
     * @mbggenerated
     */
    public void setCommentId(Integer commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column axin_blogs_reply.reply_type
     *
     * @return the value of axin_blogs_reply.reply_type
     *
     * @mbggenerated
     */
    public Byte getReplyType() {
        return replyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column axin_blogs_reply.reply_type
     *
     * @param replyType the value for axin_blogs_reply.reply_type
     *
     * @mbggenerated
     */
    public void setReplyType(Byte replyType) {
        this.replyType = replyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column axin_blogs_reply.reply_id
     *
     * @return the value of axin_blogs_reply.reply_id
     *
     * @mbggenerated
     */
    public Integer getReplyId() {
        return replyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column axin_blogs_reply.reply_id
     *
     * @param replyId the value for axin_blogs_reply.reply_id
     *
     * @mbggenerated
     */
    public void setReplyId(Integer replyId) {
        this.replyId = replyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column axin_blogs_reply.to_uid
     *
     * @return the value of axin_blogs_reply.to_uid
     *
     * @mbggenerated
     */
    public Integer getToUid() {
        return toUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column axin_blogs_reply.to_uid
     *
     * @param toUid the value for axin_blogs_reply.to_uid
     *
     * @mbggenerated
     */
    public void setToUid(Integer toUid) {
        this.toUid = toUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column axin_blogs_reply.from_uid
     *
     * @return the value of axin_blogs_reply.from_uid
     *
     * @mbggenerated
     */
    public Integer getFromUid() {
        return fromUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column axin_blogs_reply.from_uid
     *
     * @param fromUid the value for axin_blogs_reply.from_uid
     *
     * @mbggenerated
     */
    public void setFromUid(Integer fromUid) {
        this.fromUid = fromUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column axin_blogs_reply.from_thumb_img
     *
     * @return the value of axin_blogs_reply.from_thumb_img
     *
     * @mbggenerated
     */
    public String getFromThumbImg() {
        return fromThumbImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column axin_blogs_reply.from_thumb_img
     *
     * @param fromThumbImg the value for axin_blogs_reply.from_thumb_img
     *
     * @mbggenerated
     */
    public void setFromThumbImg(String fromThumbImg) {
        this.fromThumbImg = fromThumbImg == null ? null : fromThumbImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column axin_blogs_reply.from_nickname
     *
     * @return the value of axin_blogs_reply.from_nickname
     *
     * @mbggenerated
     */
    public String getFromNickname() {
        return fromNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column axin_blogs_reply.from_nickname
     *
     * @param fromNickname the value for axin_blogs_reply.from_nickname
     *
     * @mbggenerated
     */
    public void setFromNickname(String fromNickname) {
        this.fromNickname = fromNickname == null ? null : fromNickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column axin_blogs_reply.create_time
     *
     * @return the value of axin_blogs_reply.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column axin_blogs_reply.create_time
     *
     * @param createTime the value for axin_blogs_reply.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column axin_blogs_reply.to_nickname
     *
     * @return the value of axin_blogs_reply.to_nickname
     *
     * @mbggenerated
     */
    public String getToNickname() {
        return toNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column axin_blogs_reply.to_nickname
     *
     * @param toNickname the value for axin_blogs_reply.to_nickname
     *
     * @mbggenerated
     */
    public void setToNickname(String toNickname) {
        this.toNickname = toNickname == null ? null : toNickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column axin_blogs_reply.is_author
     *
     * @return the value of axin_blogs_reply.is_author
     *
     * @mbggenerated
     */
    public Byte getIsAuthor() {
        return isAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column axin_blogs_reply.is_author
     *
     * @param isAuthor the value for axin_blogs_reply.is_author
     *
     * @mbggenerated
     */
    public void setIsAuthor(Byte isAuthor) {
        this.isAuthor = isAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column axin_blogs_reply.content
     *
     * @return the value of axin_blogs_reply.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column axin_blogs_reply.content
     *
     * @param content the value for axin_blogs_reply.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}