package club.renxl.www.blog.article.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ReplyExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table axin_blogs_reply
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table axin_blogs_reply
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table axin_blogs_reply
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table axin_blogs_reply
     *
     * @mbggenerated
     */
    public ReplyExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table axin_blogs_reply
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table axin_blogs_reply
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table axin_blogs_reply
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table axin_blogs_reply
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table axin_blogs_reply
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table axin_blogs_reply
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table axin_blogs_reply
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table axin_blogs_reply
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table axin_blogs_reply
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table axin_blogs_reply
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table axin_blogs_reply
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCommentIdIsNull() {
            addCriterion("comment_id is null");
            return (Criteria) this;
        }

        public Criteria andCommentIdIsNotNull() {
            addCriterion("comment_id is not null");
            return (Criteria) this;
        }

        public Criteria andCommentIdEqualTo(Long value) {
            addCriterion("comment_id =", value, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdNotEqualTo(Long value) {
            addCriterion("comment_id <>", value, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdGreaterThan(Long value) {
            addCriterion("comment_id >", value, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdGreaterThanOrEqualTo(Long value) {
            addCriterion("comment_id >=", value, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdLessThan(Long value) {
            addCriterion("comment_id <", value, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdLessThanOrEqualTo(Long value) {
            addCriterion("comment_id <=", value, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdIn(List<Long> values) {
            addCriterion("comment_id in", values, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdNotIn(List<Long> values) {
            addCriterion("comment_id not in", values, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdBetween(Long value1, Long value2) {
            addCriterion("comment_id between", value1, value2, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdNotBetween(Long value1, Long value2) {
            addCriterion("comment_id not between", value1, value2, "commentId");
            return (Criteria) this;
        }

        public Criteria andReplyTypeIsNull() {
            addCriterion("reply_type is null");
            return (Criteria) this;
        }

        public Criteria andReplyTypeIsNotNull() {
            addCriterion("reply_type is not null");
            return (Criteria) this;
        }

        public Criteria andReplyTypeEqualTo(Byte value) {
            addCriterion("reply_type =", value, "replyType");
            return (Criteria) this;
        }

        public Criteria andReplyTypeNotEqualTo(Byte value) {
            addCriterion("reply_type <>", value, "replyType");
            return (Criteria) this;
        }

        public Criteria andReplyTypeGreaterThan(Byte value) {
            addCriterion("reply_type >", value, "replyType");
            return (Criteria) this;
        }

        public Criteria andReplyTypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("reply_type >=", value, "replyType");
            return (Criteria) this;
        }

        public Criteria andReplyTypeLessThan(Byte value) {
            addCriterion("reply_type <", value, "replyType");
            return (Criteria) this;
        }

        public Criteria andReplyTypeLessThanOrEqualTo(Byte value) {
            addCriterion("reply_type <=", value, "replyType");
            return (Criteria) this;
        }

        public Criteria andReplyTypeIn(List<Byte> values) {
            addCriterion("reply_type in", values, "replyType");
            return (Criteria) this;
        }

        public Criteria andReplyTypeNotIn(List<Byte> values) {
            addCriterion("reply_type not in", values, "replyType");
            return (Criteria) this;
        }

        public Criteria andReplyTypeBetween(Byte value1, Byte value2) {
            addCriterion("reply_type between", value1, value2, "replyType");
            return (Criteria) this;
        }

        public Criteria andReplyTypeNotBetween(Byte value1, Byte value2) {
            addCriterion("reply_type not between", value1, value2, "replyType");
            return (Criteria) this;
        }

        public Criteria andReplyIdIsNull() {
            addCriterion("reply_id is null");
            return (Criteria) this;
        }

        public Criteria andReplyIdIsNotNull() {
            addCriterion("reply_id is not null");
            return (Criteria) this;
        }

        public Criteria andReplyIdEqualTo(Long value) {
            addCriterion("reply_id =", value, "replyId");
            return (Criteria) this;
        }

        public Criteria andReplyIdNotEqualTo(Long value) {
            addCriterion("reply_id <>", value, "replyId");
            return (Criteria) this;
        }

        public Criteria andReplyIdGreaterThan(Long value) {
            addCriterion("reply_id >", value, "replyId");
            return (Criteria) this;
        }

        public Criteria andReplyIdGreaterThanOrEqualTo(Long value) {
            addCriterion("reply_id >=", value, "replyId");
            return (Criteria) this;
        }

        public Criteria andReplyIdLessThan(Long value) {
            addCriterion("reply_id <", value, "replyId");
            return (Criteria) this;
        }

        public Criteria andReplyIdLessThanOrEqualTo(Long value) {
            addCriterion("reply_id <=", value, "replyId");
            return (Criteria) this;
        }

        public Criteria andReplyIdIn(List<Long> values) {
            addCriterion("reply_id in", values, "replyId");
            return (Criteria) this;
        }

        public Criteria andReplyIdNotIn(List<Long> values) {
            addCriterion("reply_id not in", values, "replyId");
            return (Criteria) this;
        }

        public Criteria andReplyIdBetween(Long value1, Long value2) {
            addCriterion("reply_id between", value1, value2, "replyId");
            return (Criteria) this;
        }

        public Criteria andReplyIdNotBetween(Long value1, Long value2) {
            addCriterion("reply_id not between", value1, value2, "replyId");
            return (Criteria) this;
        }

        public Criteria andToUidIsNull() {
            addCriterion("to_uid is null");
            return (Criteria) this;
        }

        public Criteria andToUidIsNotNull() {
            addCriterion("to_uid is not null");
            return (Criteria) this;
        }

        public Criteria andToUidEqualTo(Long value) {
            addCriterion("to_uid =", value, "toUid");
            return (Criteria) this;
        }

        public Criteria andToUidNotEqualTo(Long value) {
            addCriterion("to_uid <>", value, "toUid");
            return (Criteria) this;
        }

        public Criteria andToUidGreaterThan(Long value) {
            addCriterion("to_uid >", value, "toUid");
            return (Criteria) this;
        }

        public Criteria andToUidGreaterThanOrEqualTo(Long value) {
            addCriterion("to_uid >=", value, "toUid");
            return (Criteria) this;
        }

        public Criteria andToUidLessThan(Long value) {
            addCriterion("to_uid <", value, "toUid");
            return (Criteria) this;
        }

        public Criteria andToUidLessThanOrEqualTo(Long value) {
            addCriterion("to_uid <=", value, "toUid");
            return (Criteria) this;
        }

        public Criteria andToUidIn(List<Long> values) {
            addCriterion("to_uid in", values, "toUid");
            return (Criteria) this;
        }

        public Criteria andToUidNotIn(List<Long> values) {
            addCriterion("to_uid not in", values, "toUid");
            return (Criteria) this;
        }

        public Criteria andToUidBetween(Long value1, Long value2) {
            addCriterion("to_uid between", value1, value2, "toUid");
            return (Criteria) this;
        }

        public Criteria andToUidNotBetween(Long value1, Long value2) {
            addCriterion("to_uid not between", value1, value2, "toUid");
            return (Criteria) this;
        }

        public Criteria andFromUidIsNull() {
            addCriterion("from_uid is null");
            return (Criteria) this;
        }

        public Criteria andFromUidIsNotNull() {
            addCriterion("from_uid is not null");
            return (Criteria) this;
        }

        public Criteria andFromUidEqualTo(Long value) {
            addCriterion("from_uid =", value, "fromUid");
            return (Criteria) this;
        }

        public Criteria andFromUidNotEqualTo(Long value) {
            addCriterion("from_uid <>", value, "fromUid");
            return (Criteria) this;
        }

        public Criteria andFromUidGreaterThan(Long value) {
            addCriterion("from_uid >", value, "fromUid");
            return (Criteria) this;
        }

        public Criteria andFromUidGreaterThanOrEqualTo(Long value) {
            addCriterion("from_uid >=", value, "fromUid");
            return (Criteria) this;
        }

        public Criteria andFromUidLessThan(Long value) {
            addCriterion("from_uid <", value, "fromUid");
            return (Criteria) this;
        }

        public Criteria andFromUidLessThanOrEqualTo(Long value) {
            addCriterion("from_uid <=", value, "fromUid");
            return (Criteria) this;
        }

        public Criteria andFromUidIn(List<Long> values) {
            addCriterion("from_uid in", values, "fromUid");
            return (Criteria) this;
        }

        public Criteria andFromUidNotIn(List<Long> values) {
            addCriterion("from_uid not in", values, "fromUid");
            return (Criteria) this;
        }

        public Criteria andFromUidBetween(Long value1, Long value2) {
            addCriterion("from_uid between", value1, value2, "fromUid");
            return (Criteria) this;
        }

        public Criteria andFromUidNotBetween(Long value1, Long value2) {
            addCriterion("from_uid not between", value1, value2, "fromUid");
            return (Criteria) this;
        }

        public Criteria andFromThumbImgIsNull() {
            addCriterion("from_thumb_img is null");
            return (Criteria) this;
        }

        public Criteria andFromThumbImgIsNotNull() {
            addCriterion("from_thumb_img is not null");
            return (Criteria) this;
        }

        public Criteria andFromThumbImgEqualTo(String value) {
            addCriterion("from_thumb_img =", value, "fromThumbImg");
            return (Criteria) this;
        }

        public Criteria andFromThumbImgNotEqualTo(String value) {
            addCriterion("from_thumb_img <>", value, "fromThumbImg");
            return (Criteria) this;
        }

        public Criteria andFromThumbImgGreaterThan(String value) {
            addCriterion("from_thumb_img >", value, "fromThumbImg");
            return (Criteria) this;
        }

        public Criteria andFromThumbImgGreaterThanOrEqualTo(String value) {
            addCriterion("from_thumb_img >=", value, "fromThumbImg");
            return (Criteria) this;
        }

        public Criteria andFromThumbImgLessThan(String value) {
            addCriterion("from_thumb_img <", value, "fromThumbImg");
            return (Criteria) this;
        }

        public Criteria andFromThumbImgLessThanOrEqualTo(String value) {
            addCriterion("from_thumb_img <=", value, "fromThumbImg");
            return (Criteria) this;
        }

        public Criteria andFromThumbImgLike(String value) {
            addCriterion("from_thumb_img like", value, "fromThumbImg");
            return (Criteria) this;
        }

        public Criteria andFromThumbImgNotLike(String value) {
            addCriterion("from_thumb_img not like", value, "fromThumbImg");
            return (Criteria) this;
        }

        public Criteria andFromThumbImgIn(List<String> values) {
            addCriterion("from_thumb_img in", values, "fromThumbImg");
            return (Criteria) this;
        }

        public Criteria andFromThumbImgNotIn(List<String> values) {
            addCriterion("from_thumb_img not in", values, "fromThumbImg");
            return (Criteria) this;
        }

        public Criteria andFromThumbImgBetween(String value1, String value2) {
            addCriterion("from_thumb_img between", value1, value2, "fromThumbImg");
            return (Criteria) this;
        }

        public Criteria andFromThumbImgNotBetween(String value1, String value2) {
            addCriterion("from_thumb_img not between", value1, value2, "fromThumbImg");
            return (Criteria) this;
        }

        public Criteria andFromNicknameIsNull() {
            addCriterion("from_nickname is null");
            return (Criteria) this;
        }

        public Criteria andFromNicknameIsNotNull() {
            addCriterion("from_nickname is not null");
            return (Criteria) this;
        }

        public Criteria andFromNicknameEqualTo(String value) {
            addCriterion("from_nickname =", value, "fromNickname");
            return (Criteria) this;
        }

        public Criteria andFromNicknameNotEqualTo(String value) {
            addCriterion("from_nickname <>", value, "fromNickname");
            return (Criteria) this;
        }

        public Criteria andFromNicknameGreaterThan(String value) {
            addCriterion("from_nickname >", value, "fromNickname");
            return (Criteria) this;
        }

        public Criteria andFromNicknameGreaterThanOrEqualTo(String value) {
            addCriterion("from_nickname >=", value, "fromNickname");
            return (Criteria) this;
        }

        public Criteria andFromNicknameLessThan(String value) {
            addCriterion("from_nickname <", value, "fromNickname");
            return (Criteria) this;
        }

        public Criteria andFromNicknameLessThanOrEqualTo(String value) {
            addCriterion("from_nickname <=", value, "fromNickname");
            return (Criteria) this;
        }

        public Criteria andFromNicknameLike(String value) {
            addCriterion("from_nickname like", value, "fromNickname");
            return (Criteria) this;
        }

        public Criteria andFromNicknameNotLike(String value) {
            addCriterion("from_nickname not like", value, "fromNickname");
            return (Criteria) this;
        }

        public Criteria andFromNicknameIn(List<String> values) {
            addCriterion("from_nickname in", values, "fromNickname");
            return (Criteria) this;
        }

        public Criteria andFromNicknameNotIn(List<String> values) {
            addCriterion("from_nickname not in", values, "fromNickname");
            return (Criteria) this;
        }

        public Criteria andFromNicknameBetween(String value1, String value2) {
            addCriterion("from_nickname between", value1, value2, "fromNickname");
            return (Criteria) this;
        }

        public Criteria andFromNicknameNotBetween(String value1, String value2) {
            addCriterion("from_nickname not between", value1, value2, "fromNickname");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andToNicknameIsNull() {
            addCriterion("to_nickname is null");
            return (Criteria) this;
        }

        public Criteria andToNicknameIsNotNull() {
            addCriterion("to_nickname is not null");
            return (Criteria) this;
        }

        public Criteria andToNicknameEqualTo(String value) {
            addCriterion("to_nickname =", value, "toNickname");
            return (Criteria) this;
        }

        public Criteria andToNicknameNotEqualTo(String value) {
            addCriterion("to_nickname <>", value, "toNickname");
            return (Criteria) this;
        }

        public Criteria andToNicknameGreaterThan(String value) {
            addCriterion("to_nickname >", value, "toNickname");
            return (Criteria) this;
        }

        public Criteria andToNicknameGreaterThanOrEqualTo(String value) {
            addCriterion("to_nickname >=", value, "toNickname");
            return (Criteria) this;
        }

        public Criteria andToNicknameLessThan(String value) {
            addCriterion("to_nickname <", value, "toNickname");
            return (Criteria) this;
        }

        public Criteria andToNicknameLessThanOrEqualTo(String value) {
            addCriterion("to_nickname <=", value, "toNickname");
            return (Criteria) this;
        }

        public Criteria andToNicknameLike(String value) {
            addCriterion("to_nickname like", value, "toNickname");
            return (Criteria) this;
        }

        public Criteria andToNicknameNotLike(String value) {
            addCriterion("to_nickname not like", value, "toNickname");
            return (Criteria) this;
        }

        public Criteria andToNicknameIn(List<String> values) {
            addCriterion("to_nickname in", values, "toNickname");
            return (Criteria) this;
        }

        public Criteria andToNicknameNotIn(List<String> values) {
            addCriterion("to_nickname not in", values, "toNickname");
            return (Criteria) this;
        }

        public Criteria andToNicknameBetween(String value1, String value2) {
            addCriterion("to_nickname between", value1, value2, "toNickname");
            return (Criteria) this;
        }

        public Criteria andToNicknameNotBetween(String value1, String value2) {
            addCriterion("to_nickname not between", value1, value2, "toNickname");
            return (Criteria) this;
        }

        public Criteria andIsAuthorIsNull() {
            addCriterion("is_author is null");
            return (Criteria) this;
        }

        public Criteria andIsAuthorIsNotNull() {
            addCriterion("is_author is not null");
            return (Criteria) this;
        }

        public Criteria andIsAuthorEqualTo(Byte value) {
            addCriterion("is_author =", value, "isAuthor");
            return (Criteria) this;
        }

        public Criteria andIsAuthorNotEqualTo(Byte value) {
            addCriterion("is_author <>", value, "isAuthor");
            return (Criteria) this;
        }

        public Criteria andIsAuthorGreaterThan(Byte value) {
            addCriterion("is_author >", value, "isAuthor");
            return (Criteria) this;
        }

        public Criteria andIsAuthorGreaterThanOrEqualTo(Byte value) {
            addCriterion("is_author >=", value, "isAuthor");
            return (Criteria) this;
        }

        public Criteria andIsAuthorLessThan(Byte value) {
            addCriterion("is_author <", value, "isAuthor");
            return (Criteria) this;
        }

        public Criteria andIsAuthorLessThanOrEqualTo(Byte value) {
            addCriterion("is_author <=", value, "isAuthor");
            return (Criteria) this;
        }

        public Criteria andIsAuthorIn(List<Byte> values) {
            addCriterion("is_author in", values, "isAuthor");
            return (Criteria) this;
        }

        public Criteria andIsAuthorNotIn(List<Byte> values) {
            addCriterion("is_author not in", values, "isAuthor");
            return (Criteria) this;
        }

        public Criteria andIsAuthorBetween(Byte value1, Byte value2) {
            addCriterion("is_author between", value1, value2, "isAuthor");
            return (Criteria) this;
        }

        public Criteria andIsAuthorNotBetween(Byte value1, Byte value2) {
            addCriterion("is_author not between", value1, value2, "isAuthor");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table axin_blogs_reply
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table axin_blogs_reply
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}