package club.renxl.www.blog.article.dao;

import java.util.List;

import org.jboss.logging.Param;

import club.renxl.www.blog.article.domain.Artitle;
import club.renxl.www.blog.article.domain.ArtitleExample;

public interface ArtitleMapper  {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table axin_blogs_artitle
     *
     * @mbggenerated
     */
    int countByExample(ArtitleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table axin_blogs_artitle
     *
     * @mbggenerated
     */
    int deleteByExample(ArtitleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table axin_blogs_artitle
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table axin_blogs_artitle
     *
     * @mbggenerated
     */
    int insert(Artitle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table axin_blogs_artitle
     *
     * @mbggenerated
     */
    int insertSelective(Artitle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table axin_blogs_artitle
     *
     * @mbggenerated
     */
    List<Artitle> selectByExampleWithBLOBs(ArtitleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table axin_blogs_artitle
     *
     * @mbggenerated
     */
    List<Artitle> selectByExample(ArtitleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table axin_blogs_artitle
     *
     * @mbggenerated
     */
    Artitle selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table axin_blogs_artitle
     *
     * @mbggenerated
     */
    int updateByExampleSelective( Artitle record,  ArtitleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table axin_blogs_artitle
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs( Artitle record, ArtitleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table axin_blogs_artitle
     *
     * @mbggenerated
     */
    int updateByExample(Artitle record,ArtitleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table axin_blogs_artitle
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Artitle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table axin_blogs_artitle
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(Artitle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table axin_blogs_artitle
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Artitle record);
}